### ISSUE TITLE
Wechat front camera can not open

### ISSUE THREAD

**Issue by ghost** [neobuddy89/android_device_oneplus_cheeseburger#1]
android O Wechat video chat front camera can not open,

I tried to fix, but I couldn't work

**Comment by neobuddy89** [comment]
This is experimental project. Will upload proper branch tonight.

**Comment by ghost** [comment]
Do you mean it will be repaired tonight?

**Comment by ghost** [comment]
Can you fix this bug?

**Comment by neobuddy89** [comment]
https://github.com/neobuddy89/android_device_oneplus_cheeseburger/tree/lineage-15.0
https://github.com/neobuddy89/cheeseburger/tree/lineage-15.0
